language: php

sudo: required

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: MCRYPT=1 PHPCS=1
    - php: 7.2
      env: MCRYPT=1 COVERAGE=1
    - php: 7.1
      env: SODIUM=1
    - php: 7.0
      env: SODIUM=1
    - php: 5.6
      env: SODIUM=1 PREFER_LOWEST=1

before_install:
  - if [[ $SODIUM == 1 ]]; then sudo add-apt-repository ppa:ondrej/php -y; sudo apt-get update -q; sudo apt-get install libsodium-dev build-essential -y; fi

install:
  - if [[ $MCRYPT == 1 ]]; then apt-get update && apt-get install libmcrypt; yes "" | pecl install -f mcrypt-1.0.2; fi
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-dist --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $SODIUM == 1 ]]; then if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then pecl install -f libsodium-1.0.6; else pecl install -f libsodium; fi; fi

script:
  - if [[ $COVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml; else vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 ./src ./tests; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash) -t d7ef710e-0649-494c-a539-d93e8c3e4b19; fi

notifications:
  email: false